### ISSUE TITLE
Recipe book scrolling works anywhere in inventory 

### ISSUE THREAD

**Issue by anoomolu** [dicedpixels/hardcover#2]
Hiya.

Maybe works as intended, but scrolling anywhere in your inventory causes the recipe book pages to flip. This can cause issues with mods like Mouse Tweaks where scrolling to move items causes the recipe book pages to fly by. I was wondering if this could be fixed so the pages only turn when the cursor is in the recipe book panel. fwiw I'm on 1.20.1 

Thanks for opening the repo back up too ^^

**Comment by dicedpixels** [comment]
Thanks for pointing this out. I don't use Mouse Tweaks, so I never noticed this, but limiting the scrolling detection isn't a bad idea. Let me see what I can do.

**Comment by dicedpixels** [comment]
Updated for 1.20/1.20.1: https://modrinth.com/mod/hardcover/version/1.0.1+fabric-mc1.20

**Comment by anoomolu** [comment]
Works perfectly, thanks a ton!
